# run: conda env create --file environment.yml
name: educhat
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
- python=3.10
- pip=23.3.0
- pytorch-cuda=11.7
- pytorch=2.0.1
- pip:
    - -r requirements.txt